spring:
  datasource:
    hikari:
      driverClassName: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/javadb?PrepareThreshold=0
      username: superuser
      password: qwe123_
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: master-pool
    pool:
      initial-size: 5
      min-idle: 5
      max-idle: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.ddl-auto: none
      hibernate.show_slq: true
      hibernate.use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

bot:
  name: my_java_interview_bot
  token: 5871503878:AAFE_lc2XOssXbCLndPwafLsotmG4RYXfHI
  owner: 1074424361

upload:
  directory: 'upload'

cron:
  scheduler: 0 1 * * * *